# Generated by hand for the initial portable schema.

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrchestratedStream",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("definition", models.JSONField()),
                ("status", models.JSONField()),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("desired_state", models.CharField(db_index=True, max_length=32)),
                ("operational_state", models.CharField(db_index=True, max_length=32)),
                (
                    "tenant_id",
                    models.CharField(blank=True, db_index=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(db_index=True)),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.CreateModel(
            name="OrchestratorEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stream_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(db_index=True, max_length=120)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(db_index=True)),
            ],
            options={"ordering": ("occurred_at", "id")},
        ),
        migrations.CreateModel(
            name="OrchestratorOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("stream_id", models.UUIDField(db_index=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="orchestratedstream",
            index=models.Index(
                fields=["desired_state", "operational_state"], name="so_desired_oper_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orchestratedstream",
            index=models.Index(fields=["tenant_id", "desired_state"], name="so_tenant_desired_idx"),
        ),
        migrations.AddIndex(
            model_name="orchestratorevent",
            index=models.Index(
                fields=["stream_id", "occurred_at"], name="so_event_stream_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orchestratoroutbox",
            index=models.Index(fields=["published_at", "created_at"], name="so_outbox_pending_idx"),
        ),
    ]
